security:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      stateless: true
      access_token:
        token_handler: Gsu\SyllabusVerification\Security\AccessTokenHandler

  access_control:
    - { path: ^/courses, roles: ROLE_USER }
    - { path: ^/filters, roles: ROLE_USER }
