<?php

declare(strict_types=1);

namespace Migrations\Gsu\SyllabusVerification;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20240805194850 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }


    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('
            CREATE TABLE CoreImpactsCourseSection (
                id INT AUTO_INCREMENT NOT NULL,
                TermCode VARCHAR(6) NOT NULL,
                TermDescription VARCHAR(30) NOT NULL,
                CollegeCode VARCHAR(4) NOT NULL,
                CollegeDescription VARCHAR(30) NOT NULL,
                DepartmentCode VARCHAR(4) NOT NULL,
                DepartmentDescription VARCHAR(30) NOT NULL,
                CRN VARCHAR(5) NOT NULL,
                SubjectCode VARCHAR(4) NOT NULL,
                CourseNumber VARCHAR(5) NOT NULL,
                SequenceNumber VARCHAR(3) NOT NULL,
                CourseTitle VARCHAR(30) NOT NULL,
                InstructorFirstName VARCHAR(120) DEFAULT NULL,
                InstructorLastName VARCHAR(120) DEFAULT NULL,
                InstructorEmail VARCHAR(30) DEFAULT NULL,
                VerifyStatus VARCHAR(10) NOT NULL,
                VerifyDate DATETIME DEFAULT NULL,
                VerifyUser VARCHAR(30) DEFAULT NULL,
                INDEX idxCoreImpactsCourseSection_01 (TermCode, CollegeCode, DepartmentCode),
                INDEX idxCoreImpactsCourseSection_02 (CRN),
                INDEX idxCoreImpactsCourseSection_03 (SubjectCode, CourseNumber, SequenceNumber),
                INDEX idxCoreImpactsCourseSection_04 (CourseTitle),
                INDEX idxCoreImpactsCourseSection_05 (InstructorFirstName, InstructorLastName),
                INDEX idxCoreImpactsCourseSection_06 (InstructorEmail),
                INDEX idxCoreImpactsCourseSection_07 (VerifyStatus),
                INDEX idxCoreImpactsCourseSection_08 (VerifyDate),
                INDEX idxCoreImpactsCourseSection_09 (VerifyUser),
                UNIQUE INDEX udxCoreImpactsCourseSection_01 (TermCode, CRN),
                PRIMARY KEY(id)
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        ');

        $this->addSql('
            CREATE TABLE CoreImpactsCourseTemplate (
                id INT AUTO_INCREMENT NOT NULL,
                ImpactAreaCode VARCHAR(1) NOT NULL,
                SubjectCode VARCHAR(4) NOT NULL,
                CourseNumber VARCHAR(5) NOT NULL,
                INDEX idxCoreImpactsCourseTemplate_01 (ImpactAreaCode),
                INDEX idxCoreImpactsCourseTemplate_02 (SubjectCode, CourseNumber),
                UNIQUE INDEX udxCoreImpactsCourseTemplate_01 (ImpactAreaCode, SubjectCode, CourseNumber),
                PRIMARY KEY(id)
            ) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB
        ');

        $this->addSql("
            INSERT IGNORE INTO CoreImpactsCourseTemplate
                (ImpactAreaCode, SubjectCode, CourseNumber)
            VALUES
                ('I', 'PERS', '2001'),
                ('I', 'PERS', '2002'),
                ('I', 'PERS', '2003'),
                ('I', 'PHIL', '1010'),
                ('I', 'SCOM', '1000'),
                ('M', 'MATH', '1001'),
                ('M', 'MATH', '1111'),
                ('M', 'MATH', '1113'),
                ('M', 'MATH', '1220'),
                ('M', 'MATH', '1401'),
                ('M', 'MATH', '2201'),
                ('M', 'MATH', '2202'),
                ('M', 'MATH', '2211'),
                ('M', 'MATH', '2212'),
                ('M', 'MATH', '2215'),
                ('M', 'MATH', '2420'),
                ('P', 'HIST', '2110'),
                ('P', 'POLS', '1101'),
                ('A', 'AH', '1700'),
                ('A', 'AH', '1750'),
                ('A', 'AH', '1850'),
                ('A', 'ARBC', '1002'),
                ('A', 'ARBC', '2001'),
                ('A', 'ARBC', '2002'),
                ('A', 'ART', '1301'),
                ('A', 'ASL', '1002'),
                ('A', 'ASL', '2001'),
                ('A', 'ASL', '2002'),
                ('A', 'CHIN', '1002'),
                ('A', 'CHIN', '2001'),
                ('A', 'CHIN', '2002'),
                ('A', 'ENGL', '2110'),
                ('A', 'ENGL', '2120'),
                ('A', 'ENGL', '2130'),
                ('A', 'FLME', '2700'),
                ('A', 'FREN', '1002'),
                ('A', 'FREN', '2001'),
                ('A', 'FREN', '2002'),
                ('A', 'GRKM', '1002'),
                ('A', 'GRKM', '2001'),
                ('A', 'GRMN', '1002'),
                ('A', 'GRMN', '2001'),
                ('A', 'GRMN', '2002'),
                ('A', 'HBRM', '1002'),
                ('A', 'HBRM', '2001'),
                ('A', 'HBRM', '2002'),
                ('A', 'HUMN', '1000'),
                ('A', 'ITAL', '1002'),
                ('A', 'ITAL', '2001'),
                ('A', 'ITAL', '2002'),
                ('A', 'JAPN', '1002'),
                ('A', 'JAPN', '2001'),
                ('A', 'JAPN', '2002'),
                ('A', 'KORE', '1002'),
                ('A', 'KORE', '2001'),
                ('A', 'KORE', '2002'),
                ('A', 'LATN', '1002'),
                ('A', 'LATN', '2001'),
                ('A', 'LATN', '2002'),
                ('A', 'MUA', '1500'),
                ('A', 'MUA', '1930'),
                ('A', 'PHIL', '2010'),
                ('A', 'PHIL', '2030'),
                ('A', 'PORT', '1002'),
                ('A', 'PORT', '2001'),
                ('A', 'PORT', '2002'),
                ('A', 'RELS', '2001'),
                ('A', 'RUSS', '1002'),
                ('A', 'RUSS', '2001'),
                ('A', 'RUSS', '2002'),
                ('A', 'SCOM', '2050'),
                ('A', 'SPAN', '1002'),
                ('A', 'SPAN', '1101'),
                ('A', 'SPAN', '2001'),
                ('A', 'SPAN', '2002'),
                ('A', 'SWAH', '1002'),
                ('A', 'SWAH', '2001'),
                ('A', 'SWAH', '2002'),
                ('A', 'THEA', '2040'),
                ('C', 'ENGL', '1101'),
                ('C', 'ENGL', '1102'),
                ('C', 'ENGL', '1103'),
                ('T', 'ASTR', '1000'),
                ('T', 'ASTR', '1010'),
                ('T', 'ASTR', '1010K'),
                ('T', 'ASTR', '1010L'),
                ('T', 'ASTR', '1020'),
                ('T', 'ASTR', '1020K'),
                ('T', 'ASTR', '1020L'),
                ('T', 'ASTR', '1500'),
                ('T', 'BIOL', '1103'),
                ('T', 'BIOL', '1103K'),
                ('T', 'BIOL', '1103L'),
                ('T', 'BIOL', '1104'),
                ('T', 'BIOL', '1104K'),
                ('T', 'BIOL', '1104L'),
                ('T', 'BIOL', '2107'),
                ('T', 'BIOL', '2107K'),
                ('T', 'BIOL', '2107L'),
                ('T', 'BIOL', '2108'),
                ('T', 'BIOL', '2108K'),
                ('T', 'BIOL', '2108L'),
                ('T', 'BIOL', '2240'),
                ('T', 'BIOL', '2300'),
                ('T', 'CHEM', '1050'),
                ('T', 'CHEM', '1151'),
                ('T', 'CHEM', '1151K'),
                ('T', 'CHEM', '1151L'),
                ('T', 'CHEM', '1152'),
                ('T', 'CHEM', '1152K'),
                ('T', 'CHEM', '1152L'),
                ('T', 'CHEM', '1211'),
                ('T', 'CHEM', '1211K'),
                ('T', 'CHEM', '1211L'),
                ('T', 'CHEM', '1212'),
                ('T', 'CHEM', '1212K'),
                ('T', 'CHEM', '1212L'),
                ('T', 'CSC1', '010'),
                ('T', 'ENVS', '1401'),
                ('T', 'ENVS', '1401K'),
                ('T', 'ENVS', '1401L'),
                ('T', 'ENVS', '1402'),
                ('T', 'ENVS', '1402K'),
                ('T', 'ENVS', '1402L'),
                ('T', 'GEOG', '1112'),
                ('T', 'GEOG', '1112L'),
                ('T', 'GEOG', '1113'),
                ('T', 'GEOG', '1113L'),
                ('T', 'GEOG', '2200'),
                ('T', 'GEOL', '1121'),
                ('T', 'GEOL', '1121K'),
                ('T', 'GEOL', '1121L'),
                ('T', 'GEOL', '1122'),
                ('T', 'GEOL', '1122K'),
                ('T', 'GEOL', '1122L'),
                ('T', 'GEOL', '2001'),
                ('T', 'MATH', '1113'),
                ('T', 'MATH', '1220'),
                ('T', 'MATH', '1401'),
                ('T', 'MATH', '2201'),
                ('T', 'MATH', '2202'),
                ('T', 'MATH', '2211'),
                ('T', 'MATH', '2212'),
                ('T', 'MATH', '2420'),
                ('T', 'NEUR', '2000'),
                ('T', 'NUTR', '2100'),
                ('T', 'PHYS', '1111'),
                ('T', 'PHYS', '1111K'),
                ('T', 'PHYS', '1111L'),
                ('T', 'PHYS', '1112'),
                ('T', 'PHYS', '1112K'),
                ('T', 'PHYS', '1112L'),
                ('T', 'PHYS', '2030'),
                ('T', 'PHYS', '2211'),
                ('T', 'PHYS', '2211K'),
                ('T', 'PHYS', '2211L'),
                ('T', 'PHYS', '2212'),
                ('T', 'PHYS', '2212K'),
                ('T', 'PHYS', '2212L'),
                ('T', 'PSYC', '1100'),
                ('S', 'AAS', '1141'),
                ('S', 'AAS', '1142'),
                ('S', 'AAS', '2010'),
                ('S', 'ANTH', '1102'),
                ('S', 'CRJU', '2200'),
                ('S', 'ECON', '2100'),
                ('S', 'ECON', '2105'),
                ('S', 'ECON', '2106'),
                ('S', 'GEOG', '1101'),
                ('S', 'GERO', '2000'),
                ('S', 'GLOS', '2401'),
                ('S', 'HIST', '1111'),
                ('S', 'HIST', '1112'),
                ('S', 'HIST', '1141'),
                ('S', 'HIST', '1142'),
                ('S', 'POLS', '2401'),
                ('S', 'PSYC', '1101'),
                ('S', 'SOCI', '1101'),
                ('S', 'SOCI', '1160'),
                ('S', 'WGSS', '2010')
        ");
    }


    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE CoreImpactsCourseSection');
        $this->addSql('DROP TABLE CoreImpactsCourseTemplate');
    }
}
